var pieces = [
    {},
    {
        id: "army_jp_g_mainland",
        "faction": JP,
        "name": "Japanese Home Islands garrison",
        "counter": "piece garrison_jp",
        "class": "ground",
        "service": "army",
        "garrison": true,
        "notreplaceable": true,
        "start_reduced": true,
        "size": 4,
        "cf": 12,
        "lf": 12,
        "rcf": 12,
    },
    {
        id: "army_jp_g_1",
        "faction": JP,
        "name": "Japanese garrison",
        "counter": "piece garrison_cn",
        "class": "ground",
        "service": "army",
        "garrison": true,
        "notreplaceable": true,
        "start_reduced": true,
        "size": 4,
        "cf": 9,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_g_2",
        "faction": JP,
        "name": "Japanese garrison",
        "counter": "piece garrison_cn",
        "class": "ground",
        "service": "army",
        "garrison": true,
        "notreplaceable": true,
        "start_reduced": true,
        "size": 4,
        "cf": 9,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_g_3",
        "faction": JP,
        "name": "Japanese garrison",
        "counter": "piece garrison_cn",
        "class": "ground",
        "service": "army",
        "garrison": true,
        "notreplaceable": true,
        "start_reduced": true,
        "size": 4,
        "cf": 9,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "hq_jp_cy",
        "faction": JP,
        "name": "Combined Fleet HQ (Yamamoto)",
        "counter": "small_units_ltyellow unit_ix_2",
        "class": "hq",
        "cr": 13,
        "cm": 3,
        "start": 3407
    },
    {
        id: "hq_jp_ss",
        "faction": JP,
        "name": "South Seas HQ",
        "counter": "small_units_ltyellow unit_ix_1",
        "class": "hq",
        "cr": 12,
        "cm": 2,
        "start": 4017
    },
    {
        id: "hq_jp_s",
        "faction": JP,
        "name": "South HQ",
        "counter": "small_units_ltyellow unit_ix_3",
        "class": "hq",
        "cr": 13,
        "cm": 1,
        "start": 2212
    },
    {
        id: "hq_jp_co",
        "faction": JP,
        "name": "Combined Fleet HQ (Ozawa)",
        "counter": "small_units_ltyellow unit_ix_4",
        "class": "hq",
        "cr": 12,
        "cm": 2,
    },
    {
        id: "akagi",
        "faction": JP,
        "name": "Akagi",
        "class": "naval",
        "type": "cv",
        "counter": "big_units_white big unit_ix_10",
        "cf": 12,
        "lf": 12,
        "br": 3,
        "rcf": 8,
        "notreplaceable": true,
        "start": 3705
    },
    {
        id: "soryu",
        "faction": JP,
        "name": "Soryu",
        "class": "naval",
        "counter": "big_units_white big unit_ix_12",
        "type": "cv",
        "cf": 10,
        "lf": 12,
        "br": 3,
        "rcf": 7,
        "notreplaceable": true,
        "start": 3705
    },
    {
        id: "shokaku",
        "faction": JP,
        "name": "Shokaku",
        "class": "naval",
        "counter": "big_units_white big unit_ix_13",
        "type": "cv",
        "cf": 14,
        "lf": 12,
        "br": 3,
        "rcf": 9,
        "notreplaceable": true,
        "start": 3705
    },
    {
        id: "zuiho",
        "faction": JP,
        "name": "Zuiho",
        "class": "naval",
        "counter": "big_units_white big unit_ix_16",
        "type": "cvl",
        "cf": 8,
        "lf": 8,
        "br": 3,
        "rcf": 6,
        "notreplaceable": true,
        "start": 3407
    },
    {
        id: "ryujo",
        "faction": JP,
        "name": "Ryujo",
        "class": "naval",
        "counter": "big_units_white big unit_ix_4",
        "type": "cvl",
        "cf": 6,
        "lf": 8,
        "br": 3,
        "rcf": 3,
        "notreplaceable": true,
        "start": 3416
    }, {
        id: "nagato",
        "faction": JP,
        "name": "Nagato",
        "class": "naval",
        "counter": "big_units_white big unit_ix_15",
        "type": "bb",
        "cf": 20,
        "lf": 14,
        "rcf": 10,
        "notreplaceable": true,
        "start": 3407
    }, {
        id: "hiei",
        "faction": JP,
        "name": "Hiei",
        "class": "naval",
        "counter": "big_units_white big unit_ix_14",
        "type": "bb",
        "cf": 17,
        "lf": 14,
        "rcf": 9,
        "notreplaceable": true,
        "start": 3705
    }, {
        id: "kongo",
        "faction": JP,
        "name": "Kongo",
        "class": "naval",
        "counter": "big_units_white big unit_ix_19",
        "type": "bb",
        "cf": 13,
        "lf": 14,
        "rcf": 7,
        "notreplaceable": true,
        "start": 2909
    }, {
        id: "aoba",
        "faction": JP,
        "name": "Aoba",
        "class": "naval",
        "counter": "big_units_white big unit_ix_17",
        "type": "ca",
        "organic": true,
        "cf": 12,
        "lf": 10,
        "rcf": 7,
        "notreplaceable": true,
        "start": 4017
    }, {
        id: "mogami",
        "faction": JP,
        "name": "Mogami",
        "class": "naval",
        "counter": "big_units_white big unit_ix_5",
        "type": "ca",
        "organic": true,
        "cf": 12,
        "lf": 10,
        "rcf": 7,
        "notreplaceable": true,
        "start": 2311
    },
    {
        id: "takao",
        "faction": JP,
        "class": "naval",
        "notreplaceable": true,
        "counter": "big_units_white big unit_ix_1",
        "start": 2909,
        "name": "Takao",
        "type": "ca",
        "organic": true,
        "cf": 12,
        "lf": 10,
        "rcf": 7,
    },
    {
        id: "nachi",
        "faction": JP,
        "class": "naval",
        "notreplaceable": true,
        "counter": "big_units_white big unit_ix_3",
        "start": 3416,
        "name": "Nachi",
        "type": "ca",
        "organic": true,
        "cf": 10,
        "lf": 10,
        "rcf": 6,
    },
    {
        id: "kamikaze",
        "faction": JP,
        "class": "naval",
        "notreplaceable": true,
        "counter": "big_units_white big unit_ix_18",
        "start": 4017,
        "name": "Kamikaze",
        "type": "apd",
        "organic": true,
        "cf": 8,
        "lf": 8,
        "rcf": 4,
    },
    {
        id: "tenyru",
        "faction": JP,
        "class": "naval",
        "notreplaceable": true,
        "counter": "big_units_white big unit_ix_2",
        "start": 4715,
        "name": "Tenyru",
        "type": "cl",
        "organic": true,
        "cf": 4,
        "lf": 8,
        "rcf": 3,
    },
    {
        id: "air_jp_21",
        "faction": JP,
        "name": "21st Air Flotilla",
        "counter": "small_units_white unit_ix_11",
        "class": "air",
        "service": "navy",
        "notreplaceable": true,
        "start": 3009,
        "cf": 16,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 8,
    },
    {
        id: "air_jp_22",
        "faction": JP,
        "name": "22nd Air Flotilla",
        "counter": "small_units_white unit_ix_12",
        "class": "air",
        "service": "navy",
        "notreplaceable": true,
        "start": 2212,
        "cf": 20,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 10,
    },
    {
        id: "air_jp_23",
        "faction": JP,
        "name": "23rd Air Flotilla",
        "counter": "small_units_white unit_ix_13",
        "class": "air",
        "service": "navy",
        "notreplaceable": true,
        "start": 3009,
        "cf": 16,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 8,
    },
    {
        id: "air_jp_24",
        "faction": JP,
        "name": "24th Air Flotilla",
        "counter": "small_units_white unit_ix_14",
        "class": "air",
        "service": "navy",
        "notreplaceable": true,
        "start": 4715,
        "cf": 10,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 5,
    },
    {
        id: "army_jp_1sn",
        "faction": JP,
        "name": "1st SN Brigade",
        "counter": "small_units_white unit_ix_3",
        "class": "ground",
        "service": "navy",
        "notreplaceable": true,
        "start": 2909,
        "size": 1,
        "cf": 4,
        "lf": 6,
        "rcf": 2,
        "organic": true,
    },
    {
        id: "army_jp_2sn",
        "faction": JP,
        "name": "2nd SN Brigade",
        "counter": "small_units_white unit_ix_4",
        "class": "ground",
        "service": "navy",
        "notreplaceable": true,
        "start": 2311,
        "size": 1,
        "cf": 4,
        "lf": 6,
        "rcf": 2,
        "organic": true,
    },
    {
        id: "army_jp_3sn",
        "faction": JP,
        "name": "3rd SN Brigade",
        "counter": "small_units_white unit_ix_5",
        "class": "ground",
        "service": "navy",
        "notreplaceable": true,
        "start": 4017,
        "size": 1,
        "cf": 4,
        "lf": 6,
        "rcf": 2,
        "organic": true,
    },
    {
        id: "army_jp_4sn",
        "faction": JP,
        "name": "4th SN Brigade",
        "counter": "small_units_white unit_ix_7",
        "class": "ground",
        "service": "navy",
        "notreplaceable": true,
        "start": 4715,
        "size": 1,
        "cf": 4,
        "lf": 6,
        "rcf": 2,
        "organic": true,
    },
    {
        id: "army_jp_ss",
        "faction": JP,
        "name": "South Seas Brigade",
        "counter": "small_units_white unit_ix_6",
        "class": "ground",
        "service": "navy",
        "notreplaceable": true,
        "start": 4017,
        "size": 1,
        "cf": 6,
        "lf": 6,
        "rcf": 3,
        "organic": true,
    },
    {
        id: "army_jp_kor",
        "faction": JP,
        "name": "Korean Army",
        "counter": "small_units_yellow unit_ix_20",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "start": 3305,
        "size": 4,
        "cf": 18,
        "lf": 18,
        "rcf": 9,
    },
    {
        id: "army_jp_ed",
        "faction": JP,
        "name": "Eastern District Army",
        "counter": "small_units_yellow unit_ix_3",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "start": 3706,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_14",
        "faction": JP,
        "name": "14th Army",
        "counter": "small_units_yellow unit_ix_18",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "start": 2909,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_15",
        "faction": JP,
        "name": "15th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_12",
        "start": 2211,
        "size": 4,
        "cf": 20,
        "lf": 12,
        "rcf": 10,
    },
    {
        id: "army_jp_16",
        "faction": JP,
        "name": "16th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_21",
        "start": 3416,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_17",
        "faction": JP,
        "name": "17th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_16",
        "start": 2708,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_18",
        "faction": JP,
        "name": "18th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_4",
        "start": 3706,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_19",
        "faction": JP,
        "name": "19th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_19",
        "start": 3209,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_25",
        "faction": JP,
        "name": "25th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_14",
        "start": 2509,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_27",
        "faction": JP,
        "name": "27th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_1",
        "start": 3704,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_35",
        "faction": JP,
        "name": "35th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_17",
        "start": 3007,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_38",
        "faction": JP,
        "name": "38th Army",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "counter": "small_units_yellow unit_ix_2",
        "start": 2211,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "air_jp_1",
        "faction": JP,
        "name": "1st Air Division",
        "class": "air",
        "service": "army",
        "notreplaceable": true,
        "counter": "small_units_yellow_air unit_ix_1",
        "start": 3706,
        "cf": 20,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 10,
    },
    {
        id: "air_jp_2",
        "faction": JP,
        "name": "2nd Air Division",
        "counter": "small_units_yellow_air unit_ix_2",
        "class": "air",
        "service": "army",
        "notreplaceable": true,
        "start": 3004,
        "cf": 20,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 10,
    },
    {
        id: "air_jp_3",
        "faction": JP,
        "name": "3rd Air Division",
        "counter": "small_units_yellow_air unit_ix_3",
        "class": "air",
        "service": "army",
        "notreplaceable": true,
        "start": 3607,
        "cf": 20,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 10,
    },
    {
        id: "air_jp_4",
        "faction": JP,
        "name": "4th Air Division",
        "counter": "small_units_yellow_air unit_ix_4",
        "class": "air",
        "service": "army",
        "notreplaceable": true,
        "start": 3607,
        "cf": 20,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 10,
    },
    {
        id: "air_jp_5",
        "faction": JP,
        "name": "5th Air Division",
        "counter": "small_units_yellow_air unit_ix_5",
        "class": "air",
        "service": "army",
        "notreplaceable": true,
        "start": 2909,
        "cf": 22,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 11,
    },
    {
        id: "air_jp_25",
        "faction": JP,
        "name": "25th Air Flotilla",
        "counter": "small_units_white unit_ix_15",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 2,
        "cf": 10,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 5,
    },
    {
        id: "air_jp_26",
        "faction": JP,
        "name": "26th Air Flotilla",
        "counter": "small_units_white unit_ix_16",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 3,
        "cf": 10,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 5,
    },
    {
        id: "air_jp_27",
        "faction": JP,
        "name": "27th Air Flotilla",
        "counter": "small_units_white unit_ix_17",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 4,
        "cf": 10,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 5,
    },
    {
        id: "air_jp_28",
        "faction": JP,
        "name": "28th Air Flotilla",
        "counter": "small_units_white unit_ix_18",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 5,
        "cf": 10,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 5,
    },
    {
        id: "air_jp_50",
        "faction": JP,
        "name": "50th Air Flotilla",
        "counter": "small_units_white unit_ix_19",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 6,
        "cf": 8,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 4,
    },
    {
        id: "air_jp_51",
        "faction": JP,
        "name": "51st Air Flotilla",
        "counter": "small_units_white unit_ix_20",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 6,
        "cf": 8,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 4,
    },
    {
        id: "air_jp_61",
        "faction": JP,
        "name": "61st Air Flotilla",
        "counter": "small_units_white unit_ix_1",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 8,
        "cf": 8,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 4,
    },
    {
        id: "air_jp_62",
        "faction": JP,
        "name": "62nd Air Flotilla",
        "counter": "small_units_white unit_ix_2",
        "class": "air",
        "service": "navy",
        "rptype": "jp_air",
        "reinforcement": 8,
        "cf": 8,
        "lf": 10,
        "br": 3,
        "ebr": 5,
        "rcf": 4,
    },
    {
        id: "air_jp_t",
        "faction": JP,
        "name": "Tainan Air Unit",
        "counter": "small_units_yellow_air unit_ix_13",
        "class": "air",
        "service": "army",
        "notreplaceable": true,
        "parenthetical": true,
        "cf": 8,
        "lf": 10,
        "br": 4,
        "ebr": 5,
        "rcf": 6,
    },
    {
        id: "air_jp_6",
        "faction": JP,
        "name": "6th Air Division",
        "counter": "small_units_yellow_air unit_ix_6",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 3,
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_jp_7",
        "faction": JP,
        "name": "7th Air Division",
        "counter": "small_units_yellow_air unit_ix_7",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 4,
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_jp_8",
        "faction": JP,
        "name": "8th Air Division",
        "counter": "small_units_yellow_air unit_ix_8",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 5,
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_jp_9",
        "faction": JP,
        "name": "9th Air Division",
        "counter": "small_units_yellow_air unit_ix_9",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 6,
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_jp_10",
        "faction": JP,
        "name": "10th Air Division",
        "counter": "small_units_yellow_air unit_ix_10",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 7,
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_jp_11",
        "faction": JP,
        "name": "11th Air Division",
        "counter": "small_units_yellow_air unit_ix_11",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 8,
        "cf": 6,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 3,
    },
    {
        id: "air_jp_12",
        "faction": JP,
        "name": "12th Air Division",
        "counter": "small_units_yellow_air unit_ix_12",
        "class": "air",
        "service": "army",
        "rptype": "jp_air",
        "reinforcement": 9,
        "cf": 6,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 3,
    },
    {
        id: "army_jp_28",
        "faction": JP,
        "name": "28th Army",
        "counter": "small_units_yellow unit_ix_5",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 2,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_31",
        "faction": JP,
        "name": "31st Army",
        "counter": "small_units_yellow unit_ix_6",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 3,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_37",
        "faction": JP,
        "name": "37th Army",
        "counter": "small_units_yellow unit_ix_7",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 4,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_33",
        "faction": JP,
        "name": "33rd Army",
        "counter": "small_units_yellow unit_ix_8",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 5,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_2",
        "faction": JP,
        "name": "2nd Army",
        "counter": "small_units_yellow unit_ix_9",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 7,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_29",
        "faction": JP,
        "name": "29th Army",
        "counter": "small_units_yellow unit_ix_10",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 8,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_32",
        "faction": JP,
        "name": "32nd Army",
        "counter": "small_units_yellow unit_ix_11",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 9,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_36",
        "faction": JP,
        "name": "36th Army",
        "counter": "small_units_yellow unit_ix_15",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 10,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "army_jp_39",
        "faction": JP,
        "name": "39th Army",
        "counter": "small_units_yellow unit_ix_13",
        "class": "ground",
        "service": "army",
        "rptype": "jp_ground",
        "reinforcement": 10,
        "start_reduced": true,
        "size": 4,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
    },
    {
        id: "yamato",
        "faction": JP,
        "name": "Yamato",
        "class": "naval",
        "counter": "big_units_white big unit_ix_6",
        "type": "bb",
        "cf": 18,
        "lf": 18,
        "rcf": 9,
        "reinforcement": 2,
        "rptype": "jp_navy",
        "start_reduced": true,
    },
    {
        id: "junyo",
        "faction": JP,
        "name": "Junyo",
        "class": "naval",
        "counter": "big_units_white big unit_ix_7",
        "type": "cv",
        "cf": 8,
        "lf": 8,
        "br": 3,
        "rcf": 6,
        "reinforcement": 3,
        "rptype": "jp_navy",
    },
    {
        id: "kaiyo",
        "faction": JP,
        "name": "Kaiyo",
        "class": "naval",
        "counter": "big_units_white big unit_ix_8",
        "type": "cve",
        "cf": 8,
        "lf": 8,
        "br": 3,
        "rcf": 6,
        "reinforcement": 7,
        "start_reduced": true,
        "rptype": "jp_navy",
    },
    {
        id: "taiho",
        "faction": JP,
        "name": "Taiho",
        "class": "naval",
        "counter": "big_units_white big unit_ix_9",
        "type": "cv",
        "cf": 10,
        "lf": 12,
        "br": 3,
        "rcf": 7,
        "reinforcement": 8,
        "rptype": "jp_navy",
    },
    {
        id: "amagi",
        "faction": JP,
        "name": "Amagi",
        "class": "naval",
        "counter": "big_units_white big unit_ix_11",
        "type": "cvl",
        "cf": 8,
        "lf": 8,
        "br": 3,
        "rcf": 6,
        "reinforcement": 9,
        "rptype": "jp_navy",
    },
    {
        id: "hq_ap_c",
        "faction": AP,
        "name": "Central Pacific HQ",
        "counter": "small_units_turquoise unit_ix_1",
        "class": "hq",
        "service": "us",
        "cr": 25,
        "cm": 3,
        "start": 5808
    },
    {
        id: "hq_ap_sw",
        "faction": AP,
        "name": "South West Pacific HQ",
        "counter": "small_units_turquoise unit_ix_2",
        "class": "hq",
        "service": "us",
        "cr": 20,
        "cm": 2,
        "start": 2813
    },
    {
        id: "hq_ap_sg",
        "faction": AP,
        "name": "South Pacific HQ (Ghormley)",
        "counter": "small_units_turquoise unit_ix_3",
        "class": "hq",
        "service": "us",
        "cr": 7,
        "cm": 1,
        "reinforcement": 3,
    },
    {
        id: "hq_ap_sh",
        "faction": AP,
        "name": "South Pacific HQ (Halsey)",
        "counter": "small_units_turquoise unit_ix_4",
        "class": "hq",
        "service": "us",
        "cr": 10,
        "cm": 3,
    },
    {
        id: "hq_ap_m",
        "faction": AP,
        "name": "Malaya HQ",
        "counter": "small_units_beige unit_ix_4",
        "class": "hq",
        "service": "br",
        "cr": 5,
        "cm": 1,
        "start": 2015,
        "notreplaceable": true,
    },
    {
        id: "hq_ap_seac",
        "faction": AP,
        "name": "SEAC HQ",
        "counter": "small_units_beige unit_ix_5",
        "class": "hq",
        "service": "br",
        "cr": 10,
        "cm": 1,
        "reinforcement": 2,
    },
    {
        id: "hq_ap_abda",
        "faction": AP,
        "name": "ABDA HQ",
        "counter": "small_units_dkblue unit_ix_1",
        "class": "hq",
        "service": "joint",
        "cr": 12,
        "cm": 1,
        "notreplaceable": true,
    },
    {
        id: "hq_ap_anzac",
        "faction": AP,
        "name": "ANZAC HQ",
        "counter": "small_units_dkblue unit_ix_2",
        "class": "hq",
        "service": "joint",
        "cr": 10,
        "cm": 1,
        "reinforcement": 3,
    },
    {
        id: "lexington",
        "faction": AP,
        "name": "Lexington",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "counter": "big_units_blue big unit_ix_3",
        "cf": 12,
        "lf": 12,
        "br": 2,
        "rcf": 8,
        "rptype": "us_navy",
        "start": 5410,
        "start_reduced": true,
    },
    {
        id: "enterprise",
        "faction": AP,
        "name": "Enterprise",
        "counter": "big_units_blue big unit_ix_4",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 12,
        "lf": 12,
        "br": 2,
        "rcf": 8,
        "rptype": "us_navy",
        "start": 5809,
        "start_reduced": true,
    },
    {
        id: "mdca",
        "faction": AP,
        "name": "MD/CA",
        "class": "naval",
        "counter": "big_units_blue big unit_ix_5",
        "type": "bb",
        "service": "navy",
        "start": 5808,
        "cf": 15,
        "lf": 10,
        "rcf": 9,
        "notreplaceable": true,
    },
    {
        id: "orleans",
        "faction": AP,
        "name": "New Orleans",
        "class": "naval",
        "counter": "big_units_blue big unit_ix_7",
        "type": "ca",
        "service": "navy",
        "start": 5808,
        "cf": 9,
        "lf": 8,
        "rcf": 6,
        "notreplaceable": true,
    },
    {
        id: "casia",
        "faction": AP,
        "name": "US Asia (Cruiser)",
        "counter": "big_units_blue big unit_ix_2",
        "class": "naval",
        "type": "ca",
        "service": "navy",
        "start": 3014,
        "cf": 4,
        "lf": 6,
        "rcf": 2,
        "notreplaceable": true,
    },
    {
        id: "dasia",
        "faction": AP,
        "name": "Us Asia (Destroyer)",
        "counter": "big_units_blue big unit_ix_1",
        "class": "naval",
        "type": "dd",
        "service": "navy",
        "start": 2616,
        "cf": 2,
        "lf": 4,
        "rcf": 1,
        "notreplaceable": true,
    },
    {
        id: "forcez",
        "faction": AP,
        "name": "Force Z",
        "counter": "big_units_beige big unit_ix_1",
        "class": "naval",
        "service": "br",
        "type": "bb",
        "start": 2015,
        "cf": 8,
        "lf": 10,
        "rcf": 4,
        "notreplaceable": true,
    },
    {
        id: "exeter",
        "faction": AP,
        "name": "Exeter",
        "counter": "big_units_beige big unit_ix_3",
        "class": "naval",
        "service": "br",
        "type": "ca",
        "start": 1307,
        "cf": 5,
        "lf": 8,
        "rcf": 3,
        "notreplaceable": true,
    },
    {
        id: "kent",
        "faction": AP,
        "name": "Kent",
        "class": "naval",
        "counter": "big_units_beige big unit_ix_2",
        "service": "au",
        "type": "ca",
        "start": 3727,
        "cf": 3,
        "lf": 8,
        "rcf": 2,
        "notreplaceable": true,
    },
    {
        id: "dutch",
        "faction": AP,
        "name": "Dutch",
        "class": "naval",
        "counter": "big_units_orange big unit_ix_1",
        "service": "du",
        "type": "cl",
        "start": 2019,
        "cf": 3,
        "lf": 8,
        "rcf": 2,
        "notreplaceable": true,
    },
    {
        id: "air_ap_211",
        "faction": AP,
        "name": "Marine Fighter Attack Squadron 211",
        "counter": "small_units_blue unit_ix_1",
        "class": "air",
        "service": "navy",
        "parenthetical": true,
        "notreplaceable": true,
        "start_reduced": true,
        "start": 4612,
        "cf": 1,
        "lf": 8,
        "rcf": 1,
        "br": 2,
        "ebr": 4,
    },
    {
        id: "air_ap_feaf",
        "faction": AP,
        "name": "Far East Air Force (US)",
        "counter": "small_units_green_air unit_ix_1",
        "class": "air",
        "service": "army",
        "parenthetical": true,
        "notreplaceable": true,
        "start": 2812,
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_ap_19_lrb",
        "faction": AP,
        "name": "19th LRB air unit",
        "counter": "small_units_green_air unit_ix_2",
        "class": "air",
        "service": "army",
        "type": "lrb",
        "notreplaceable": true,
        "start": 2812,
        "cf": 2,
        "lf": 9,
        "br": 6,
        "rcf": 1,
    },
    {
        id: "air_ap_7",
        "faction": AP,
        "name": "7th Air Force",
        "class": "air",
        "service": "army",
        "counter": "small_units_green_air unit_ix_3",
        "rptype": "ap_air",
        "start": 5808,
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
    },
    {
        id: "air_ap_7_lrb",
        "faction": AP,
        "name": "7th Air Force (LRB)",
        "counter": "small_units_green_air unit_ix_4",
        "class": "air",
        "service": "army",
        "type": "lrb",
        "rptype": "ap_air",
        "start": 5808,
        "cf": 4,
        "lf": 10,
        "br": 6,
        "ebr": 6,
        "rcf": 2,
    },
    {
        id: "air_ap_avg",
        "faction": AP,
        "name": "The American Volunteer Groups",
        "counter": "small_units_green_air unit_ix_16",
        "class": "air",
        "service": "army",
        "parenthetical": true,
        "notreplaceable": true,
        "start": 2008,
        "cf": 6,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
    },
    {
        id: "air_ap_du",
        "faction": AP,
        "name": "Royal Netherlands Air Force",
        "counter": "small_units_orange unit_ix_1",
        "class": "air",
        "service": "du",
        "parenthetical": true,
        "notreplaceable": true,
        "start": 2019,
        "cf": 7,
        "lf": 9,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_ap_fe",
        "faction": AP,
        "name": "Far East Air Force (RAF)",
        "counter": "small_units_beige_air unit_ix_3",
        "class": "air",
        "service": "br",
        "parenthetical": true,
        "notreplaceable": true,
        "start": 1905,
        "cf": 7,
        "lf": 9,
        "br": 2,
        "ebr": 4,
        "rcf": 4,
    },
    {
        id: "air_ap_ma",
        "faction": AP,
        "name": "Malayan Air Force (RAF)",
        "counter": "small_units_beige_air unit_ix_4",
        "class": "air",
        "service": "br",
        "parenthetical": true,
        "notreplaceable": true,
        "start": 2015,
        "cf": 6,
        "lf": 9,
        "br": 2,
        "ebr": 4,
        "rcf": 3,
    },
    {
        id: "air_ap_au",
        "faction": AP,
        "name": "Australian Air Force",
        "counter": "small_units_beige_air unit_ix_5",
        "class": "air",
        "service": "au",
        "parenthetical": true,
        "rptype": "ap_air",
        "start": 3727,
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
    },
    {
        id: "air_ap_14",
        "faction": AP,
        "name": "14th Air Force",
        "counter": "small_units_green_air unit_ix_15",
        "class": "air",
        "service": "army",
        "rptype": "ap_air",
        "cf": 9,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 6,
    },
    {
        id: "air_ap_10_lrb",
        "faction": AP,
        "name": "10th Air Force (LRB)",
        "counter": "small_units_green_air unit_ix_5",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "reinforcement": 2,
        "cf": 4,
        "lf": 10,
        "br": 6,
        "rcf": 2,
    },
    {
        id: "air_ap_5_lrb",
        "faction": AP,
        "name": "5th Air Force (LRB)",
        "counter": "small_units_green_air unit_ix_7",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "reinforcement": 2,
        "cf": 4,
        "lf": 10,
        "br": 6,
        "rcf": 2,
    },
    {
        id: "air_ap_5",
        "faction": AP,
        "name": "5th Air Force",
        "counter": "small_units_green_air unit_ix_6",
        "class": "air",
        "service": "army",
        "rptype": "ap_air",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
        "reinforcement": 2,
    },
    {
        id: "air_ap_1_maw",
        "faction": AP,
        "name": "1st Marine Aircraft Wing",
        "counter": "small_units_blue unit_ix_3",
        "class": "air",
        "service": "navy",
        "parenthetical": true,
        "rptype": "ap_air",
        "cf": 6,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 3,
        "reinforcement": 2,
    },
    {
        id: "air_ap_seac",
        "faction": AP,
        "name": "SEAC Air Force",
        "counter": "small_units_beige_air unit_ix_1",
        "class": "air",
        "service": "br",
        "rptype": "ap_air",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
        "reinforcement": 2,
    },
    {
        id: "air_ap_seac_lrb",
        "faction": AP,
        "name": "SEAC Air Force (LRB)",
        "counter": "small_units_beige_air unit_ix_2",
        "class": "air",
        "type": "lrb",
        "service": "br",
        "rptype": "ap_air",
        "cf": 4,
        "lf": 10,
        "br": 6,
        "rcf": 2,
        "reinforcement": 5,
    },
    {
        id: "air_ap_13_lrb",
        "faction": AP,
        "name": "13th Air Force (LRB)",
        "counter": "small_units_green_air unit_ix_9",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "reinforcement": 3,
        "cf": 4,
        "lf": 10,
        "br": 6,
        "rcf": 2,
    },
    {
        id: "air_ap_13",
        "faction": AP,
        "name": "13th Air Force",
        "counter": "small_units_green_air unit_ix_8",
        "class": "air",
        "service": "army",
        "rptype": "ap_air",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
        "reinforcement": 3,
    },
    {
        id: "air_ap_11_lrb",
        "faction": AP,
        "name": "11th Air Force (LRB)",
        "counter": "small_units_green_air unit_ix_11",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "reinforcement": 3,
        "cf": 4,
        "lf": 10,
        "br": 6,
        "rcf": 2,
    },
    {
        id: "air_ap_11",
        "faction": AP,
        "name": "11th Air Force",
        "counter": "small_units_green_air unit_ix_10",
        "class": "air",
        "service": "army",
        "rptype": "ap_air",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 5,
        "reinforcement": 3,
    },
    {
        id: "air_ap_14_lrb",
        "faction": AP,
        "name": "14th Air Force (LRB)",
        "counter": "small_units_green_air unit_ix_12",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "reinforcement": 4,
        "cf": 4,
        "lf": 10,
        "br": 6,
        "rcf": 2,
    },
    {
        id: "air_ap_2_maw",
        "faction": AP,
        "name": "2nd Marine Aircraft Wing",
        "counter": "small_units_blue unit_ix_4",
        "class": "air",
        "service": "navy",
        "parenthetical": true,
        "rptype": "ap_air",
        "cf": 8,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 6,
        "reinforcement": 4,
    },
    {
        id: "air_ap_3_maw",
        "faction": AP,
        "name": "3rd Marine Aircraft Wing",
        "counter": "small_units_blue unit_ix_5",
        "class": "air",
        "service": "navy",
        "parenthetical": true,
        "rptype": "ap_air",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "ebr": 4,
        "rcf": 8,
        "reinforcement": 9,
    },
    {
        id: "air_ap_20_bc",
        "faction": AP,
        "name": "XX Bomber Command (B-29)",
        "counter": "small_units_green_air unit_ix_13",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "cf": 6,
        "lf": 10,
        "br": 8,
        "rcf": 3,
        "reinforcement": 9,
        "b29": 1,
    },
    {
        id: "air_ap_21_bc",
        "faction": AP,
        "name": "XXI Bomber Command (B-29)",
        "counter": "small_units_green_air unit_ix_14",
        "class": "air",
        "type": "lrb",
        "service": "army",
        "rptype": "ap_air",
        "cf": 6,
        "lf": 10,
        "br": 8,
        "rcf": 3,
        "reinforcement": 10,
        "b29": 4,
    },
    {
        id: "mississippi",
        "faction": AP,
        "name": "Mississippi",
        "counter": "big_units_blue big unit_ix_6",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 2,
        "cf": 15,
        "lf": 12,
        "rcf": 7,
        "rptype": "us_navy",
    },
    {
        id: "northampton",
        "faction": AP,
        "name": "Northampton",
        "counter": "big_units_blue big unit_ix_8",
        "class": "naval",
        "type": "ca",
        "service": "navy",
        "reinforcement": 2,
        "cf": 9,
        "lf": 8,
        "rcf": 6,
        "rptype": "us_navy",
    },
    {
        id: "warspite",
        "faction": AP,
        "name": "Warspite",
        "counter": "big_units_beige big unit_ix_6",
        "class": "naval",
        "type": "bb",
        "service": "br",
        "reinforcement": 2,
        "cf": 14,
        "lf": 14,
        "rcf": 7,
        "rptype": "com_navy",
    },
    {
        id: "indomitable",
        "faction": AP,
        "name": "Indomitable",
        "counter": "big_units_beige big unit_ix_5",
        "class": "naval",
        "type": "cv",
        "service": "br",
        "reinforcement": 2,
        "cf": 10,
        "lf": 12,
        "br": 2,
        "rcf": 5,
        "rptype": "com_navy",
    },
    {
        id: "hermes",
        "faction": AP,
        "name": "Hermes",
        "class": "naval",
        "counter": "big_units_beige big unit_ix_7",
        "type": "cvl",
        "service": "br",
        "reinforcement": 2,
        "cf": 2,
        "lf": 8,
        "br": 2,
        "rcf": 2,
        "notreplaceable": true,
        "start_reduced": true,
    },
    {
        id: "carolina",
        "faction": AP,
        "name": "North Carolina",
        "counter": "big_units_blue big unit_ix_10",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 3,
        "cf": 16,
        "lf": 16,
        "rcf": 8,
        "rptype": "us_navy",
    },
    {
        id: "wasp",
        "faction": AP,
        "name": "Wasp",
        "class": "naval",
        "counter": "big_units_blue big unit_ix_9",
        "type": "cv",
        "service": "navy",
        "cf": 12,
        "lf": 12,
        "br": 2,
        "rcf": 8,
        "rptype": "us_navy",
        "reinforcement": 3,
    },
    {
        id: "washington",
        "faction": AP,
        "name": "Washington",
        "counter": "big_units_blue big unit_ix_11",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 4,
        "cf": 16,
        "lf": 16,
        "rcf": 8,
        "rptype": "us_navy",
    },
    {
        id: "london",
        "faction": AP,
        "name": "London",
        "class": "naval",
        "counter": "big_units_beige big unit_ix_8",
        "type": "ca",
        "service": "br",
        "reinforcement": 4,
        "cf": 6,
        "lf": 8,
        "rcf": 3,
        "rptype": "com_navy",
    },
    {
        id: "mass",
        "faction": AP,
        "name": "Massachusetts",
        "counter": "big_units_blue big unit_ix_12",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 5,
        "cf": 16,
        "lf": 16,
        "rcf": 8,
        "rptype": "us_navy",
    },
    {
        id: "jacinto",
        "faction": AP,
        "name": "San Jacinto",
        "counter": "big_units_blue big unit_ix_13",
        "class": "naval",
        "type": "cvl",
        "service": "navy",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "rcf": 7,
        "rptype": "us_navy",
        "reinforcement": 5,
    },
    {
        id: "essex",
        "faction": AP,
        "name": "Essex",
        "class": "naval",
        "counter": "big_units_blue big unit_ix_14",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 6,
    },
    {
        id: "bunker",
        "faction": AP,
        "name": "Bunker Hill",
        "counter": "big_units_blue big unit_ix_18",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 6,
    },
    {
        id: "cowpens",
        "faction": AP,
        "name": "Cowpens",
        "counter": "big_units_blue big unit_ix_17",
        "class": "naval",
        "type": "cvl",
        "service": "navy",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "rcf": 7,
        "rptype": "us_navy",
        "reinforcement": 6,
    },
    {
        id: "belleau",
        "faction": AP,
        "name": "Belleau Wood",
        "counter": "big_units_blue big unit_ix_15",
        "class": "naval",
        "type": "cvl",
        "service": "navy",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "rcf": 7,
        "rptype": "us_navy",
        "reinforcement": 6,
    },
    {
        id: "sangamon",
        "faction": AP,
        "name": "Sangamon",
        "counter": "big_units_blue big unit_ix_16",
        "class": "naval",
        "type": "cve",
        "service": "navy",
        "cf": 6,
        "lf": 8,
        "br": 2,
        "rcf": 3,
        "rptype": "us_navy",
        "reinforcement": 6,
    },
    {
        id: "jersey",
        "faction": AP,
        "name": "New Jersey",
        "counter": "big_units_blue big unit_ix_22",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 7,
        "cf": 16,
        "lf": 16,
        "rcf": 8,
        "rptype": "us_navy",
    },
    {
        id: "franklin",
        "faction": AP,
        "name": "Franklin",
        "counter": "big_units_blue big unit_ix_21",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 7,
    },
    {
        id: "intrepid",
        "faction": AP,
        "name": "Intrepid",
        "counter": "big_units_blue big unit_ix_20",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 7,
    },
    {
        id: "bataan",
        "faction": AP,
        "name": "Bataan",
        "class": "naval",
        "counter": "big_units_blue big unit_ix_19",
        "type": "cvl",
        "service": "navy",
        "cf": 10,
        "lf": 10,
        "br": 2,
        "rcf": 7,
        "rptype": "us_navy",
        "reinforcement": 7,
    },
    {
        id: "hancock",
        "faction": AP,
        "counter": "big_units_blue big unit_ix_24",
        "name": "Hancock",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 8,
    },
    {
        id: "casablanca",
        "faction": AP,
        "name": "Casablanca",
        "counter": "big_units_blue big unit_ix_23",
        "class": "naval",
        "type": "cve",
        "service": "navy",
        "cf": 6,
        "lf": 8,
        "br": 2,
        "rcf": 3,
        "rptype": "us_navy",
        "reinforcement": 8,
    },
    {
        id: "shangri",
        "faction": AP,
        "name": "Shangri-La",
        "counter": "big_units_blue big unit_ix_27",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 9,
    },
    {
        id: "missouri",
        "faction": AP,
        "name": "Missouri",
        "counter": "big_units_blue big unit_ix_26",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 9,
        "cf": 16,
        "lf": 16,
        "rcf": 8,
        "rptype": "us_navy",
    },
    {
        id: "newyork",
        "faction": AP,
        "name": "New York",
        "counter": "big_units_blue big unit_ix_25",
        "class": "naval",
        "type": "bb",
        "service": "navy",
        "reinforcement": 9,
        "cf": 16,
        "lf": 16,
        "rcf": 8,
        "rptype": "us_navy",
    },
    {
        id: "richard",
        "faction": AP,
        "name": "B.H. Richard",
        "counter": "big_units_blue big unit_ix_30",
        "class": "naval",
        "type": "cv",
        "service": "navy",
        "cf": 14,
        "lf": 14,
        "br": 2,
        "rcf": 10,
        "rptype": "us_navy",
        "reinforcement": 10,
    },
    {
        id: "alaska",
        "faction": AP,
        "name": "Alaska",
        "class": "naval",
        "counter": "big_units_blue big unit_ix_29",
        "type": "bc",
        "service": "navy",
        "reinforcement": 10,
        "cf": 10,
        "lf": 12,
        "rcf": 5,
        "rptype": "us_navy",
    },
    {
        id: "stlo",
        "faction": AP,
        "name": "St. Lo",
        "counter": "big_units_blue big unit_ix_28",
        "class": "naval",
        "type": "cve",
        "service": "navy",
        "cf": 6,
        "lf": 8,
        "br": 2,
        "rcf": 3,
        "rptype": "us_navy",
        "reinforcement": 10,
    },
    {
        id: "cbay",
        "faction": AP,
        "name": "Commencement Bay",
        "counter": "big_units_blue big unit_ix_32",
        "class": "naval",
        "type": "cve",
        "service": "navy",
        "cf": 6,
        "lf": 8,
        "br": 2,
        "rcf": 3,
        "rptype": "us_navy",
        "reinforcement": 10,
    },
    {
        id: "baltimore",
        "faction": AP,
        "name": "Baltimore",
        "counter": "big_units_blue big unit_ix_31",
        "class": "naval",
        "type": "ca",
        "service": "navy",
        "cf": 8,
        "lf": 10,
        "rcf": 4,
        "rptype": "us_navy",
        "reinforcement": 11,
    },
    {
        id: "duke",
        "faction": AP,
        "name": "Duke of York",
        "counter": "big_units_beige big unit_ix_4",
        "class": "naval",
        "type": "bb",
        "service": "br",
        "cf": 20,
        "lf": 16,
        "rcf": 10,
        "rptype": "com_navy",
        "reinforcement": 10,
    },
    {
        id: "victorious",
        "faction": AP,
        "name": "Victorious",
        "counter": "big_units_beige big unit_ix_9",
        "class": "naval",
        "type": "cv",
        "service": "br",
        "cf": 12,
        "lf": 14,
        "br": 2,
        "rcf": 6,
        "rptype": "com_navy",
        "reinforcement": 10,
    },
    {
        id: "army_ap_5_cn",
        "faction": AP,
        "name": "Chinese 5th Army",
        "counter": "small_units_red unit_ix_2",
        "class": "ground",
        "service": "ch",
        "rptype": "ch_ground",
        "start": 2407,
        "size": 4,
        "cf": 5,
        "lf": 12,
        "rcf": 3,
        "start_reduced": true,
    },
    {
        id: "army_ap_6_cn",
        "faction": AP,
        "name": "Chinese 6th Army",
        "counter": "small_units_red unit_ix_3",
        "class": "ground",
        "service": "ch",
        "rptype": "ch_ground",
        "start": 2407,
        "size": 4,
        "cf": 5,
        "lf": 12,
        "rcf": 3,
        "start_reduced": true,
    },
    {
        id: "army_ap_66_cn",
        "faction": AP,
        "name": "Chinese 66th Army",
        "counter": "small_units_red unit_ix_1",
        "class": "ground",
        "service": "ch",
        "rptype": "ch_ground",
        "start": 2407,
        "size": 4,
        "cf": 6,
        "lf": 12,
        "rcf": 4,
        "start_reduced": true,
    },
    {
        id: "army_ap_w",
        "faction": AP,
        "name": "Wake Island Brigade",
        "class": "ground",
        "counter": "small_units_blue unit_ix_2",
        "type": "marine",
        "service": "navy",
        "start": 4612,
        "size": 1,
        "cf": 2,
        "lf": 6,
        "rcf": 2,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_nl",
        "faction": AP,
        "name": "NL Corps",
        "counter": "small_units_green unit_ix_1",
        "class": "ground",
        "service": "army",
        "start": 2812,
        "size": 3,
        "cf": 6,
        "lf": 10,
        "rcf": 3,
        "notreplaceable": true,
    },
    {
        id: "army_ap_r",
        "faction": AP,
        "name": "R Corps",
        "counter": "small_units_green unit_ix_2",
        "class": "ground",
        "service": "army",
        "start": 2813,
        "size": 3,
        "cf": 10,
        "lf": 10,
        "rcf": 5,
        "notreplaceable": true,
    },
    {
        id: "army_ap_sl",
        "faction": AP,
        "name": "SL Corps",
        "counter": "small_units_green unit_ix_3",
        "class": "ground",
        "service": "army",
        "start": 2913,
        "size": 3,
        "cf": 4,
        "lf": 10,
        "rcf": 2,
        "notreplaceable": true,
    },
    {
        id: "army_ap_m",
        "faction": AP,
        "name": "M Corps",
        "class": "ground",
        "counter": "small_units_green unit_ix_4",
        "service": "army",
        "start": 2915,
        "size": 3,
        "cf": 3,
        "lf": 10,
        "rcf": 1,
        "notreplaceable": true,
    },
    {
        id: "army_ap_p",
        "faction": AP,
        "name": "P Brigade",
        "counter": "small_units_green unit_ix_5",
        "class": "ground",
        "service": "army",
        "start": 3014,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_10",
        "faction": AP,
        "name": "X Corps",
        "counter": "small_units_green unit_ix_6",
        "class": "ground",
        "service": "army",
        "start": 5808,
        "size": 3,
        "cf": 18,
        "lf": 12,
        "rcf": 9,
        "rptype": "ap_ground",
    },
    {
        id: "army_ap_1_au",
        "faction": AP,
        "name": "1st Australian Corps",
        "counter": "small_units_beige unit_ix_8",
        "class": "ground",
        "service": "au",
        "start": 3023,
        "size": 3,
        "cf": 12,
        "lf": 12,
        "rcf": 6,
        "rptype": "ap_ground",
    },
    {
        id: "army_ap_2_au",
        "faction": AP,
        "name": "2nd Australian Corps",
        "counter": "small_units_beige unit_ix_9",
        "class": "ground",
        "service": "au",
        "start": 3727,
        "size": 3,
        "cf": 12,
        "lf": 12,
        "rcf": 6,
        "rptype": "ap_ground",
    },
    {
        id: "army_ap_8_au",
        "faction": AP,
        "name": "8th Australian Division",
        "counter": "small_units_beige unit_ix_7",
        "class": "ground",
        "service": "au",
        "start": 2015,
        "size": 2,
        "cf": 6,
        "lf": 12,
        "rcf": 3,
        "notreplaceable": true,
    },
    {
        id: "army_ap_pm",
        "faction": AP,
        "name": "PM Brigade",
        "counter": "small_units_beige unit_ix_10",
        "class": "ground",
        "service": "au",
        "start": 3823,
        "size": 1,
        "cf": 5,
        "lf": 5,
        "rcf": 3,
        "notreplaceable": true,
    },
    {
        id: "army_ap_hk",
        "faction": AP,
        "name": "Hong Kong Division",
        "counter": "small_units_beige unit_ix_1",
        "class": "ground",
        "service": "br",
        "start": 2709,
        "size": 2,
        "cf": 3,
        "lf": 4,
        "rcf": 1,
        "notreplaceable": true,
    },
    {
        id: "army_ap_3_ind",
        "faction": AP,
        "name": "3rd Indian Corps",
        "counter": "small_units_beige unit_ix_18",
        "class": "ground",
        "service": "ind",
        "start": 2014,
        "size": 3,
        "cf": 9,
        "lf": 9,
        "rcf": 5,
        "notreplaceable": true,
    },
    {
        id: "army_ap_b_ind",
        "faction": AP,
        "name": "Burma Indian Division",
        "counter": "small_units_beige unit_ix_19",
        "class": "ground",
        "service": "bu",
        "start": 2008,
        "size": 2,
        "cf": 3,
        "lf": 5,
        "rcf": 1,
        "notreplaceable": true,
    },
    {
        id: "army_ap_1_bu",
        "faction": AP,
        "name": "1st Burma Division",
        "counter": "small_units_beige unit_ix_15",
        "class": "ground",
        "service": "bu",
        "start": 2108,
        "size": 2,
        "cf": 6,
        "lf": 4,
        "rcf": 3,
        "notreplaceable": true,
    },
    {
        id: "army_ap_1_ind",
        "faction": AP,
        "name": "1st Indian Corps",
        "counter": "small_units_beige unit_ix_16",
        "class": "ground",
        "service": "ind",
        "start": 2105,
        "size": 3,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "notreplaceable": true,
    },
    {
        id: "army_ap_2_ind",
        "faction": AP,
        "name": "2nd Indian Corps",
        "counter": "small_units_beige unit_ix_17",
        "class": "ground",
        "service": "ind",
        "start": 1905,
        "size": 3,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "notreplaceable": true,
    },
    {
        id: "army_ap_1_du",
        "faction": AP,
        "name": "1st Regiment",
        "counter": "small_units_orange unit_ix_2",
        "class": "ground",
        "service": "du",
        "start": 1916,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_2_du",
        "faction": AP,
        "name": "2nd Regiment",
        "counter": "small_units_orange unit_ix_3",
        "class": "ground",
        "service": "du",
        "start": 1813,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_3_du",
        "faction": AP,
        "name": "3rd Regiment",
        "counter": "small_units_orange unit_ix_4",
        "class": "ground",
        "service": "du",
        "start": 2616,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_4_du",
        "faction": AP,
        "name": "4th Regiment",
        "counter": "small_units_orange unit_ix_5",
        "class": "ground",
        "service": "du",
        "start": 2919,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_5_du",
        "faction": AP,
        "name": "5th Regiment",
        "counter": "small_units_orange unit_ix_6",
        "class": "ground",
        "service": "du",
        "start": 2517,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_6_du",
        "faction": AP,
        "name": "6th Regiment",
        "counter": "small_units_orange unit_ix_7",
        "class": "ground",
        "service": "du",
        "start": 2917,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_7_du",
        "faction": AP,
        "name": "7th Regiment",
        "class": "ground",
        "counter": "small_units_orange unit_ix_8",
        "service": "du",
        "start": 2719,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_8_du",
        "faction": AP,
        "name": "8th Regiment",
        "counter": "small_units_orange unit_ix_9",
        "class": "ground",
        "service": "du",
        "start": 2721,
        "size": 1,
        "cf": 1,
        "lf": 6,
        "rcf": 1,
        "start_reduced": true,
        "notreplaceable": true,
    },
    {
        id: "army_ap_j",
        "faction": AP,
        "name": "Java Division",
        "counter": "small_units_orange unit_ix_10",
        "class": "ground",
        "service": "du",
        "start": 2019,
        "size": 2,
        "cf": 6,
        "lf": 12,
        "rcf": 3,
        "notreplaceable": true,
    },
    {
        id: "army_ap_7",
        "faction": AP,
        "name": "7th Armored Brigade",
        "class": "ground",
        "counter": "small_units_beige unit_ix_14",
        "service": "br",
        "size": 1,
        "cf": 4,
        "lf": 10,
        "rcf": 2,
        "rptype": "ap_ground"
    },
    {
        id: "army_ap_77",
        "faction": AP,
        "name": "77th Brigade",
        "counter": "small_units_beige unit_ix_6",
        "class": "ground",
        "service": "br",
        "size": 1,
        "cf": 6,
        "lf": 6,
        "rcf": 4,
        "rptype": "ap_ground"
    },
    {
        id: "army_ap_4_m",
        "faction": AP,
        "name": "4th Marine Division",
        "counter": "small_units_blue unit_ix_8",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 2,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground"
    },
    {
        id: "army_ap_11",
        "faction": AP,
        "name": "XI Corps",
        "class": "ground",
        "counter": "small_units_green unit_ix_9",
        "service": "army",
        "size": 3,
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rptype": "ap_ground",
        "reinforcement": 2,
    },
    {
        id: "army_ap_14",
        "faction": AP,
        "name": "XIV Corps",
        "counter": "small_units_green unit_ix_8",
        "class": "ground",
        "service": "army",
        "size": 3,
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rptype": "ap_ground",
        "reinforcement": 3,
        "start_reduced": true,
    },
    {
        id: "army_ap_1",
        "faction": AP,
        "name": "I Corps",
        "class": "ground",
        "service": "army",
        "counter": "small_units_green unit_ix_7",
        "size": 3,
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rptype": "ap_ground",
        "reinforcement": 3,
        "start_reduced": true,
    },
    {
        id: "army_ap_24",
        "faction": AP,
        "name": "XXIV Corps",
        "counter": "small_units_green unit_ix_10",
        "class": "ground",
        "service": "army",
        "size": 3,
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rptype": "ap_ground",
        "reinforcement": 5,
    },
    {
        id: "army_ap_9",
        "faction": AP,
        "name": "IX Corps",
        "counter": "small_units_green unit_ix_11",
        "class": "ground",
        "service": "army",
        "size": 3,
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rptype": "ap_ground",
        "reinforcement": 8,
    },
    {
        id: "army_ap_11_d",
        "faction": AP,
        "name": "11th Airborne Division",
        "counter": "small_units_green unit_ix_12",
        "class": "ground",
        "service": "army",
        "size": 2,
        "cf": 9,
        "lf": 12,
        "rcf": 6,
        "rptype": "ap_ground",
        "reinforcement": 8,
    },
    {
        id: "army_ap_mb",
        "faction": AP,
        "name": "Marine Brigade",
        "counter": "small_units_blue unit_ix_6",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 1,
        "cf": 8,
        "lf": 8,
        "rcf": 4,
        "rptype": "ap_ground",
        "reinforcement": 2,
    },
    {
        id: "army_ap_sf",
        "faction": AP,
        "name": "SF Brigade",
        "counter": "small_units_blue unit_ix_7",
        "class": "ground",
        "service": "navy",
        "size": 1,
        "cf": 4,
        "lf": 6,
        "rcf": 2,
        "rptype": "ap_ground",
        "reinforcement": 2,
    },
    {
        id: "army_ap_1_m",
        "faction": AP,
        "name": "1st Marine Division",
        "counter": "small_units_blue unit_ix_8",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 2,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 3,
    },
    {
        id: "army_ap_2_m",
        "faction": AP,
        "name": "2nd Marine Division",
        "counter": "small_units_blue unit_ix_9",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 2,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 4,
    },
    {
        id: "army_ap_3_m",
        "faction": AP,
        "name": "3rd Marine Division",
        "counter": "small_units_blue unit_ix_10",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 2,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 6,
    },
    {
        id: "army_ap_6_m",
        "faction": AP,
        "name": "6th Marine Division",
        "counter": "small_units_blue unit_ix_11",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 2,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 8,
    },
    {
        id: "army_ap_5_m",
        "faction": AP,
        "name": "5th Marine Division",
        "counter": "small_units_blue unit_ix_12",
        "class": "ground",
        "type": "marine",
        "service": "navy",
        "size": 2,
        "cf": 12,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 10,
    },
    {
        id: "army_ap_15",
        "faction": AP,
        "name": "15th Corps",
        "class": "ground",
        "counter": "small_units_beige unit_ix_2",
        "service": "br",
        "size": 3,
        "cf": 16,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 3,
    },
    {
        id: "army_ap_33",
        "faction": AP,
        "name": "33rd Corps",
        "counter": "small_units_beige unit_ix_3",
        "class": "ground",
        "service": "br",
        "size": 3,
        "cf": 20,
        "lf": 12,
        "rcf": 10,
        "rptype": "ap_ground",
        "reinforcement": 3,
    },
    {
        id: "army_ap_3_au",
        "faction": AP,
        "name": "3rd Australian Corps",
        "class": "ground",
        "counter": "small_units_beige unit_ix_11",
        "service": "au",
        "size": 3,
        "cf": 22,
        "lf": 12,
        "rcf": 11,
        "rptype": "ap_ground",
        "reinforcement": 3,
    },
    {
        id: "army_ap_3_nz",
        "faction": AP,
        "name": "3rd New Zealand Division",
        "counter": "small_units_beige unit_ix_12",
        "class": "ground",
        "service": "br",
        "size": 2,
        "cf": 9,
        "lf": 12,
        "rcf": 6,
        "rptype": "ap_ground",
        "reinforcement": 3,
    },
    {
        id: "army_ap_4_ind",
        "faction": AP,
        "name": "4th Indian Corps",
        "counter": "small_units_beige unit_ix_20",
        "class": "ground",
        "service": "ind",
        "size": 3,
        "cf": 16,
        "lf": 12,
        "rcf": 8,
        "rptype": "ap_ground",
        "reinforcement": 4,
    },
    {
        id: "army_ap_4_au",
        "faction": AP,
        "name": "4th Australian Corps",
        "counter": "small_units_beige unit_ix_13",
        "class": "ground",
        "service": "au",
        "size": 3,
        "cf": 20,
        "lf": 12,
        "rcf": 10,
        "rptype": "ap_ground",
        "reinforcement": 8,
    },
]


// PIECES
const HQ_CENTRAL_PACIFIC = find_piece("hq_ap_c")
const HQ_SOUTH_WEST = find_piece("hq_ap_sw")
const HQ_SOUTH_GHORMLEY = find_piece("hq_ap_sg")
const HQ_SOUTH_HELSEY = find_piece("hq_ap_sh")
const HQ_MALAYA = find_piece("hq_ap_m")
const HQ_SEAC = find_piece("hq_ap_seac")
const HQ_ABDA = find_piece("hq_ap_abda")
const HQ_ANZAC = find_piece("hq_ap_anzac")

const NEW_ZEEL = find_piece("army_ap_3_nz")
const M_CORPS = find_piece("army_ap_m")
const NL_CORPS = find_piece("army_ap_nl")
const SL_CORPS = find_piece("army_ap_sl")
const HK_DIVISION = find_piece("army_ap_hk")
const US_FEAF = find_piece("air_ap_feaf")
const LRB_19 = find_piece("air_ap_19_lrb")
const LRB_10 = find_piece("air_ap_10_lrb")
const AP_AIR_14 = find_piece("air_ap_14")
const LRB_14 = find_piece("air_ap_14_lrb")
const AF7 = find_piece("air_ap_7")
const AF7_LRB = find_piece("air_ap_7_lrb")
const US_ASIA_CA = find_piece("casia")
const N_ORLEANS = find_piece("orleans")
const B_29_1 = ap_air("20_bc")
const B_29_2 = ap_air("21_bc")
const ARMOR_BRIGADE = ap_army("7")
const JP_GARRISON_JP = jp_army("g_mainland")
const JP_GARRISON_CN = [jp_army("g_1"), jp_army("g_2"), jp_army("g_3")]
const KAMIKAZE = find_piece("kamikaze")

//HQ
const HQ_YAMAMOTO = find_piece("hq_jp_cy")
const HQ_OZAWA = find_piece("hq_jp_co")
const HQ_JP_SOUTH = find_piece("hq_jp_s")
const HQ_SOUTH_SEAS = find_piece("hq_jp_ss")
const KOREAN_ARMY = find_piece("army_jp_kor")
const ED_ARMY = find_piece("army_jp_ed")

const HQ_LIST = []

for (let i = 1; i < pieces.length; i++) {
    if (pieces[i].class === "hq") {
        set_add(HQ_LIST, i)
    }
}

//Fill units data
for (var i = 1; i < pieces.length; i++) {
    const piece = pieces[i]
    piece.u = i
    const supply = piece.class === "hq" ? get_hq_supply_type(piece) : get_unit_supply_type(piece)
    piece.supply = supply
    piece.replacement = get_unit_replacement_type(piece)
    if (piece.class === "naval" && !piece.faction) {
        piece.service = "navy"
    }

    if (piece.class === "air" || piece.class === "naval" && piece.br) {
        piece.zoi_generator = 1
    }

    if (piece.start_reduced && pieces.notreplaceable) {
        piece.one_step = 1
    }
    if (!piece.ebr && piece.br) {
        piece.ebr = piece.br
    }

    if (piece.type === "lrb" && i !== LRB_19 && i !== LRB_10) {
        var pair = find_piece(piece.id.replace("_lrb", ""))
        if (pair !== i) {
            pieces[pair].pair = i
            piece.pair = pair
        }
    }

    if (i === jp_army("kor")) {
        piece.asp = 4
        piece.aspr = 2
        piece.strat_move = true
    } else if (i === ARMOR_BRIGADE) {
        piece.strat_move = true
    } else if (piece.class === "ground" && ["du", "ind", "ch", "bu"].includes(piece.service)) {
        piece.strat_move = false
    } else if (piece.class === "ground" && piece.size < 3) {
        piece.asp = 1
        piece.aspr = 1
        piece.strat_move = true
    } else if (piece.class === "ground") {
        piece.asp = 2
        piece.aspr = 1
        piece.strat_move = true
    }
}

function find_piece(id) {
    for (let i = 1; i < pieces.length; i++) {
        if (pieces[i].id === id) {
            return i
        }
    }
    throw new Error("Missed unit " + id);
}

function ap_air(id) {
    return find_piece("air_ap_" + id)
}

function ap_army(id) {
    return find_piece("army_ap_" + id)
}

function jp_air(id) {
    return find_piece("air_jp_" + id)
}

function jp_army(id) {
    return find_piece("army_jp_" + id)
}

function get_hq_supply_type(piece) {
    if (!piece.faction) {
        return JP_SUPPLIED_HEX
    } else if (piece.service === "us") {
        return US_SUPPLIED_HEX
    } else if (piece.service === "br") {
        return BR_SUPPLIED_HEX
    } else {
        return JOINT_SUPPLIED_HEX
    }
}

function get_unit_replacement_type(piece) {
    if (piece.notreplaceable || piece.class === "hq") {
        return null
    }
    if (piece.service === "ch") {
        return CHINESE_REP
    } else if (piece.class === "naval" && (piece.service === "au" || piece.service === "br")) {
        return COMMONWEALTH_REP
    } else if (piece.class === "air") {
        return AIR_REP
    } else if (piece.class === "ground") {
        return GROUND_REP
    }
    return NAVAl_REP
}

function is_commonwelth(piece) {
    return piece.service === "br" || piece.service === "au" || piece.service === "bu" || piece.service === "ind"
}

function is_us_unit(piece) {
    return (piece.service === "navy" || piece.service === "army") && piece.faction === AP
}

function get_unit_supply_type(piece) {
    if (!piece.faction) {
        return JP_SUPPLIED_HEX
    } else if (piece.service === "ch" || piece.class === "air" && (piece.service === "navy" || piece.service === "army")) {
        return AP_SUPPLIED_HEX
    } else if (is_commonwelth(piece)) {
        return BR_SUPPLIED_HEX | JOINT_SUPPLIED_HEX
    } else if (piece.service === "navy" || piece.service === "army") {
        return US_SUPPLIED_HEX | JOINT_SUPPLIED_HEX
    } else if (piece.service === "du") {
        return JOINT_SUPPLIED_HEX
    }
    throw new Error("Invalid piece supply: " + piece.name)
}