var cards = [
    {},
    {
        "num": 1,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "pw": 1,
        "remove": true,
        "name": "Battan Death March",
    },
    {
        "num": 2,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "draw": true,
        "isr_rivalry": true,
        "name": "Imperial HQ Debate",
    },
    {
        "num": 3,
        "faction": AP,
        "ops": 1,
        "type": RESOURCE,
        "oc": 1,
        "remove": true,
        "name": "Prime Minister Curtin",
    },
    {
        "num": 4,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "remove": true,
        "isr_agreement": true,
        "name": "Arcadia Conference",
    },
    {
        "num": 5,
        "faction": AP,
        "ops": 2,
        "type": COUNTER_OFFENSIVE,
        "oc": 2,
        "logistic": 3,
        "intelligence": INTERCEPT,
        "name": "Operation Matador",
    },
    {
        "num": 6,
        "faction": AP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 3,
        "remove": true,
        "pw": 1,
        "name": "Doolittle Raid",
    },
    {
        "num": 7,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "remove": true,
        "logistic": 4,
        "hq": [HQ_SEAC],
        "name": "`Vinegar` Joe Stilwell",
    },
    {
        "num": 8,
        "faction": AP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 1,
        "remove": true,
        "draw": true,
        "intelligence": INTERCEPT,
        "name": "Australian Coast Watchers",
    },
    {
        "num": 9,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 12,
        "hq": [HQ_SOUTH_WEST, HQ_CENTRAL_PACIFIC],
        "name": "Olympic and Coronet",
    },
    {
        "num": 10,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "remove": true,
        "isr_agreement": true,
        "name": "General Douglas MacArthur",
    },
    {
        "num": 11,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Minor allied victory",
        "wie": [-1, -1, -2, -3],
        "name": "War in Europe",
    },
    {
        "num": 12,
        "faction": AP,
        "ops": 2,
        "type": INTELLIGENCE,
        "oc": 2,
        "remove": true,
        "intelligence": AMBUSH,
        "name": "Commander Rochefort",
    },
    {
        "num": 13,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "intelligence": SURPRISE,
        "logistic": 5,
        "name": "Operation Watchtower",
    },
    {
        "num": 14,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Minor allied victory",
        "wie": [-1, -1, -2, -3],
        "name": "War in Europe",
    },
    {
        "num": 15,
        "faction": AP,
        "ops": 2,
        "type": RESOURCE,
        "oc": 2,
        "name": "Heroic Repair",
    },
    {
        "num": 16,
        "faction": AP,
        "ops": 1,
        "type": RESOURCE,
        "oc": 1,
        "remove": true,
        "name": "Makin Is. Raid",
    },
    {
        "num": 17,
        "faction": AP,
        "ops": 2,
        "type": RESOURCE,
        "oc": 2,
        "remove": true,
        "name": "China Airlift",
    },
    {
        "num": 18,
        "faction": AP,
        "ops": 1,
        "type": RESOURCE,
        "oc": 1,
        "remove": true,
        "name": "Edwin Booz",
    },
    {
        "num": 19,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "name": "Anakim Operation",
    },
    {
        "num": 20,
        "faction": AP,
        "ops": 1,
        "type": MILITARY,
        "oc": 1,
        "ec": 3,
        "logistic": 4,
        "hq": [HQ_SOUTH_HELSEY],
        "remove": true,
        "name": "Halsey Replaces Ghormley",
    },
    {
        "num": 21,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_SOUTH_WEST], 6],
        "name": "Operation Cartwheel",
    },
    {
        "num": 22,
        "faction": AP,
        "ops": 2,
        "type": CANCEL,
        "oc": 2,
        "remove": true,
        "name": "Orde Wingate",
    },
    {
        "num": 23,
        "faction": AP,
        "ops": 2,
        "type": RESOURCE,
        "oc": 2,
        "remove": true,
        "draw": true,
        "name": "PT Boats",
    },
    {
        "num": 24,
        "faction": AP,
        "ops": 2,
        "type": REACTION,
        "stage": BEFORE_COMBAT,
        "oc": 2,
        "remove": true,
        "draw": true,
        "name": "Skip Bombing Attack",
    },
    {
        "num": 25,
        "faction": AP,
        "ops": 1,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "hq": [HQ_SOUTH_WEST],
        "name": "Operation Lilliput",
    },
    {
        "num": 26,
        "faction": AP,
        "ops": 2,
        "type": INTELLIGENCE,
        "oc": 2,
        "remove": true,
        "intelligence": AMBUSH,
        "name": "US Army Breaks Japanese Army Codes",
    },
    {
        "num": 27,
        "faction": AP,
        "ops": 1,
        "type": RESOURCE,
        "oc": 1,
        "remove": true,
        "name": "Operation Vengeance",
    },
    {
        "num": 28,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "name": "Operation Chronicle",
    },
    {
        "num": 29,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "name": "Operation Toenails",
    },
    {
        "num": 30,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "name": "Operation Sandcrab-Cottage",
    },
    {
        "num": 31,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 6,
        "name": "Black Day",
    },
    {
        "num": 32,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_SOUTH_WEST], 7],
        "name": "Operation Reno II",
    },
    {
        "num": 33,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "name": "Quadrant Conference",
    },
    {
        "num": 34,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "hq": [HQ_SEAC, HQ_MALAYA, HQ_ANZAC, HQ_ABDA],
        "name": "Operation Culevrin",
    },
    {
        "num": 35,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "logistic": 2,
        "intelligence": SURPRISE,
        "hq": [HQ_ANZAC],
        "name": "Operation Ash",
    },
    {
        "num": 36,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 5,
        "name": "Operation Cherry Blossom",
    },
    {
        "num": 37,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "intelligence": SURPRISE,
        "logistic": 6,
        "name": "Operation Galvanic",
    },
    {
        "num": 38,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "name": "Operation Tarzan",
    },
    {
        "num": 39,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "name": "Sextant Conference",
    },
    {
        "num": 40,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 3,
        "logistic_alt": [[HQ_SOUTH_WEST], 5],
        "name": "Operation Dexterity",
    },
    {
        "num": 41,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Minor allied victory",
        "wie": [-1, -1, -2, -3],
        "name": "War in Europe",
    },
    {
        "num": 42,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Minor allied victory",
        "wie": [-1, -1, -2, -3],
        "name": "War in Europe",
    },
    {
        "num": 43,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "draw": true,
        "isr_rivalry": true,
        "name": "Japanese Army/Navy Dispute",
    },
    {
        "num": 44,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "intelligence": SURPRISE,
        "logistic": 2,
        "hq": [HQ_ANZAC],
        "name": "Operation Squarepeg",
    },
    {
        "num": 45,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 8],
        "name": "Operation Flintlock",
    },
    {
        "num": 46,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "intelligence": SURPRISE,
        "logistic": 1,
        "hq": [HQ_SOUTH_WEST],
        "name": "Operation Brewer",
    },
    {
        "num": 47,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Major allied victory",
        "wie": [-1, -2, -3, -3],
        "name": "War in Europe",
    },
    {
        "num": 48,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "logistic_alt": [[HQ_SEAC], 4],
        "name": "New China Army",
    },
    {
        "num": 49,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "remove": true,
        "china": -1,
        "name": "Roosevelt Threatens Chungking",
    },
    {
        "num": 50,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "logistic_alt": [[HQ_SOUTH_WEST], 4],
        "name": "Tornado Taskforce",
    },
    {
        "num": 51,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "remove": true,
        "name": "Chenault",
    },
    {
        "num": 52,
        "faction": AP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 1,
        "remove": true,
        "isr_agreement": true,
        "name": "Roosevelt-Nimitz-MacArthur",
    },
    {
        "num": 53,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 6],
        "name": "Operation Forager II",
    },
    {
        "num": 54,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "logistic_alt": [[HQ_SOUTH_WEST], 4],
        "name": "Hurricane Taskforce",
    },
    {
        "num": 55,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 6],
        "name": "Operation Forager",
    },
    {
        "num": 56,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "logistic_alt": [[HQ_SOUTH_WEST], 4],
        "name": "Typhoon Taskforce",
    },
    {
        "num": 57,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 5,
        "hq": [HQ_SEAC, HQ_MALAYA, HQ_ANZAC, HQ_ABDA],
        "name": "Axiom",
    },
    {
        "num": 58,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "hq": [HQ_SEAC],
        "name": "Operation Romulus",
    },
    {
        "num": 59,
        "faction": AP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 1,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "Ultra Information",
    },
    {
        "num": 60,
        "faction": AP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 3,
        "remove": true,
        "name": "20th Bomber Command",
    },
    {
        "num": 61,
        "faction": AP,
        "ops": 1,
        "type": REACTION,
        "oc": 1,
        "draw": true,
        "remove": true,
        "stage": BEFORE_COMBAT,
        "name": "Submarine Attack",
    },
    {
        "num": 62,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 6,
        "logistic_alt": [[HQ_SOUTH_WEST], 8],
        "remove": true,
        "name": "Operation King II",
    },
    {
        "num": 63,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 6],
        "name": "Operation Stalemate",
    },
    {
        "num": 64,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 3,
        "logistic_alt": [[HQ_SOUTH_WEST], 4],
        "name": "Tradewind Taskforce",
    },
    {
        "num": 65,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 6,
        "logistic_alt": [[HQ_SOUTH_WEST], 8],
        "remove": true,
        "name": "MacArthur `moral obligation`",
    },
    {
        "num": 66,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Major allied victory",
        "wie": [-1, -2, -3, -3],
        "name": "War in Europe",
    },
    {
        "num": 67,
        "faction": AP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 3,
        "remove": true,
        "name": "Curtis LeMay",
    },
    {
        "num": 68,
        "faction": AP,
        "ops": 1,
        "type": REACTION,
        "oc": 1,
        "draw": true,
        "remove": true,
        "stage": AFTER_COMBAT,
        "name": "Submarine Attack",
    },
    {
        "num": 69,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 6,
        "logistic_alt": [[HQ_SOUTH_WEST], 8],
        "name": "S-Day",
    },
    {
        "num": 70,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 6,
        "hq": [HQ_SEAC],
        "remove": true,
        "name": "Slim's Burma Offensive",
    },
    {
        "num": 71,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "logistic_alt": [[HQ_SOUTH_WEST], 6],
        "name": "Victor Plans",
    },
    {
        "num": 72,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 8],
        "name": "Halsey",
    },
    {
        "num": 73,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "cause": "Major allied victory",
        "wie": [-1, -2, -3, -3],
        "name": "War in Europe",
    },
    {
        "num": 74,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 8],
        "name": "Operation Iceberg",
    },
    {
        "num": 75,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_CENTRAL_PACIFIC], 8],
        "name": "Operation Detachment",
    },
    {
        "num": 76,
        "faction": AP,
        "ops": 2,
        "type": MILITARY,
        "oc": 2,
        "ec": 4,
        "logistic": 5,
        "name": "Oboe",
    },
    {
        "num": 77,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "remove": true,
        "china": -1,
        "name": "Mao Tse Tung",
    },
    {
        "num": 78,
        "faction": AP,
        "ops": 1,
        "type": REACTION,
        "oc": 1,
        "draw": true,
        "remove": true,
        "stage": BEFORE_COMBAT,
        "name": "Submarine Attack",
    },
    {
        "num": 79,
        "faction": AP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 3,
        "remove": true,
        "reshuffle": true,
        "name": "Soviet Invade Manchuria",
    },
    {
        "num": 80,
        "faction": AP,
        "ops": 1,
        "type": RESOURCE,
        "oc": 1,
        "remove": true,
        "draw": true,
        "name": "New Submarine Doctrine",
    },
    {
        "num": 81,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "china": -1,
        "name": "China Offensive",
    },
    {
        "num": 82,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "china": -1,
        "name": "China Offensive",
    },
    {
        "num": 83,
        "faction": AP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 2,
        "china": -1,
        "name": "China Offensive",
    },
    {
        "num": 84,
        "faction": AP,
        "ops": 3,
        "type": MILITARY,
        "oc": 3,
        "remove": true,
        "logistic": 0,
        "intelligence": SURPRISE,
        "hq": [HQ_CENTRAL_PACIFIC],
        "name": "U.S. Carrier Raids",
    },
    {
        "num": 1,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "remove": true,
        "intelligence": SURPRISE,
        "name": "Operation Z",
    },
    {
        "num": 2,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "remove": true,
        "intelligence": SURPRISE,
        "logistic": 20,
        "name": "IAI - Operation No. 1",
    },
    {
        "num": 3,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 4,
        "logistic": 3,
        "intelligence": SURPRISE,
        "name": "Col. Tsuji, Unit 82",
    },
    {
        "num": 4,
        "faction": JP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 3,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "JN25 Code Change",
    },
    {
        "num": 5,
        "faction": JP,
        "ops": 2,
        "type": RESOURCE,
        "oc": 4,
        "remove": true,
        "name": "Japanese Aircraft Production Efficiency",
    },
    {
        "num": 6,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "remove": true,
        "china": 1,
        "name": "Doolittle Raid Reprisal",
    },
    {
        "num": 7,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "draw": true,
        "isr_rivalry": true,
        "name": "US Joint Staff Debate",
    },
    {
        "num": 8,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Operation C",
    },
    {
        "num": 9,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 6,
        "name": "Rear Admiral Matami Ugaki",
    },
    {
        "num": 10,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 6,
        "name": "2nd Operational Phase",
    },
    {
        "num": 11,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "draw": true,
        "isr_rivalry": true,
        "name": "US/British Second Front Conference",
    },
    {
        "num": 12,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 8,
        "logistic": 8,
        "name": "Operation MI",
    },
    {
        "num": 13,
        "faction": JP,
        "ops": 2,
        "type": INTELLIGENCE,
        "oc": 4,
        "intelligence": INTERCEPT,
        "remove": true,
        "name": "JN25 Code Change",
    },
    {
        "num": 14,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 5,
        "name": "Operation MO",
    },
    {
        "num": 15,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "name": "Mahatma Gandhi",
    },
    {
        "num": 16,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Operation RI",
    },
    {
        "num": 17,
        "faction": JP,
        "ops": 2,
        "type": COUNTER_OFFENSIVE,
        "oc": 4,
        "logistic": 3,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "Japanese Counterattack at Savo Island",
    },
    {
        "num": 18,
        "faction": JP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 3,
        "remove": true,
        "name": "Bridge on River Kwai",
    },
    {
        "num": 19,
        "faction": JP,
        "ops": 2,
        "type": CANCEL,
        "oc": 4,
        "remove": true,
        "name": "Weather",
    },
    {
        "num": 20,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 3,
        "ec": 5,
        "logistic": 5,
        "name": "Naval Battle of Guadalcanal",
    },
    {
        "num": 21,
        "faction": JP,
        "ops": 3,
        "type": CANCEL,
        "oc": 5,
        "remove": true,
        "draw": true,
        "name": "Mahatma Gandhi",
    },
    {
        "num": 22,
        "faction": JP,
        "ops": 2,
        "type": CANCEL,
        "oc": 4,
        "remove": true,
        "name": "Weather",
    },
    {
        "num": 23,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 4,
        "ec": 6,
        "logistic": 3,
        "name": "Operation RE",
    },
    {
        "num": 24,
        "faction": JP,
        "ops": 1,
        "type": REACTION,
        "oc": 3,
        "draw": true,
        "stage": AFTER_COMBAT,
        "name": "Submarine Attack",
    },
    {
        "num": 25,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Operation KA",
    },
    {
        "num": 26,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "remove": true,
        "china": 1,
        "name": "Chiang Kai-shek",
    },
    {
        "num": 27,
        "faction": JP,
        "ops": 1,
        "type": REACTION,
        "oc": 3,
        "draw": true,
        "stage": AFTER_COMBAT,
        "name": "Submarine Attack",
    },
    {
        "num": 28,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Big Tokyo Express Operation",
    },
    {
        "num": 29,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Combined Fleet",
    },
    {
        "num": 30,
        "faction": JP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 5,
        "remove": true,
        "name": "Flight Instructors",
    },
    {
        "num": 31,
        "faction": JP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 5,
        "remove": true,
        "name": "New Operation Plan",
    },
    {
        "num": 32,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Operation I-Go",
    },
    {
        "num": 33,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "isr_agreement": true,
        "name": "Imperial Intervention",
    },
    {
        "num": 34,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "draw": true,
        "isr_rivalry": true,
        "name": "US Army/Navy Dispute",
    },
    {
        "num": 35,
        "faction": JP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 5,
        "name": "Operation KE",
    },
    {
        "num": 36,
        "faction": JP,
        "ops": 1,
        "type": REACTION,
        "oc": 3,
        "draw": true,
        "stage": BEFORE_COMBAT,
        "name": "Submarine Attack",
    },
    {
        "num": 37,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 2,
        "remove": true,
        "hq": [HQ_YAMAMOTO, HQ_OZAWA],
        "name": "1st Convoy Escort Fleet",
    },
    {
        "num": 38,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 2,
        "remove": true,
        "hq": [HQ_YAMAMOTO, HQ_OZAWA],
        "name": "Grand Escort Command",
    },
    {
        "num": 39,
        "faction": JP,
        "ops": 2,
        "type": RESOURCE,
        "oc": 4,
        "remove": true,
        "name": "Subhas Chandra Bose",
    },
    {
        "num": 40,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Operation U-Go",
    },
    {
        "num": 41,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "china": 1,
        "name": "Patrick Hurley",
    },
    {
        "num": 42,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "china": 1,
        "name": "Ichi-Go",
    },
    {
        "num": 43,
        "faction": JP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 3,
        "pw": -2,
        "remove": true,
        "reshuffle": true,
        "name": "Tojo Resigns",
    },
    {
        "num": 44,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 4,
        "name": "Tokyo Express",
    },
    {
        "num": 45,
        "faction": JP,
        "ops": 3,
        "type": COUNTER_OFFENSIVE,
        "oc": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_YAMAMOTO, HQ_OZAWA], 5],
        "intelligence": INTERCEPT,
        "remove": true,
        "name": "Operation Sho-Go",
    },
    {
        "num": 46,
        "faction": JP,
        "ops": 3,
        "type": COUNTER_OFFENSIVE,
        "oc": 5,
        "logistic": 4,
        "logistic_alt": [[HQ_YAMAMOTO, HQ_OZAWA], 5],
        "intelligence": INTERCEPT,
        "remove": true,
        "name": "Operation A-Go",
    },
    {
        "num": 47,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 7,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "name": "VADM Kondo",
    },
    {
        "num": 48,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 5,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "name": "General Adachi",
    },
    {
        "num": 49,
        "faction": JP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 3,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "JN25 Code Change",
    },
    {
        "num": 50,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 6,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "name": "Ha-Go",
    },
    {
        "num": 51,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "cause": "Minor axis victory",
        "wie": [2, 1],
        "name": "War in Europe",
    },
    {
        "num": 52,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "cause": "Minor axis victory",
        "wie": [2, 1],
        "name": "War in Europe",
    },
    {
        "num": 53,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "cause": "Minor axis victory",
        "wie": [2, 1],
        "name": "War in Europe",
    },
    {
        "num": 54,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "cause": "Minor axis victory",
        "wie": [2, 1],
        "name": "War in Europe",
    },
    {
        "num": 55,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "wie": [3, 2, 1],
        "cause": "Major axis victory",
        "name": "War in Europe",
    },
    {
        "num": 56,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "cause": "Minor axis victory",
        "wie": [2, 1],
        "name": "War in Europe",
    },
    {
        "num": 57,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "remove": true,
        "cause": "Minor axis victory",
        "wie": [2, 1],
        "name": "War in Europe",
    },
    {
        "num": 58,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 5,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "name": "Western Force",
    },
    {
        "num": 59,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 5,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "name": "Central Force",
    },
    {
        "num": 60,
        "faction": JP,
        "ops": 3,
        "type": MILITARY,
        "oc": 5,
        "ec": 7,
        "logistic": 5,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "name": "East Force",
    },
    {
        "num": 61,
        "faction": JP,
        "ops": 2,
        "type": REACTION,
        "oc": 4,
        "draw": true,
        "stage": BEFORE_COMBAT,
        "kamikaze": true,
        "remove": true,
        "name": "Kamikaze Attack",
    },
    {
        "num": 62,
        "faction": JP,
        "ops": 2,
        "type": REACTION,
        "stage": BEFORE_COMBAT,
        "oc": 4,
        "draw": true,
        "kamikaze": true,
        "remove": true,
        "name": "Kamikaze Attack",
    },
    {
        "num": 63,
        "faction": JP,
        "ops": 2,
        "type": REACTION,
        "stage": BEFORE_COMBAT,
        "oc": 4,
        "draw": true,
        "kamikaze": true,
        "remove": true,
        "name": "Kamikaze Attack",
    },
    {
        "num": 64,
        "faction": JP,
        "ops": 2,
        "type": CANCEL,
        "oc": 4,
        "draw": true,
        "remove": true,
        "name": "Weather",
    },
    {
        "num": 65,
        "faction": JP,
        "ops": 1,
        "type": COUNTER_OFFENSIVE,
        "oc": 4,
        "intelligence": INTERCEPT,
        "remove": true,
        "name": "Yamato Suicide Run",
    },
    {
        "num": 66,
        "faction": JP,
        "ops": 2,
        "type": REACTION,
        "stage": BEFORE_COMBAT,
        "oc": 4,
        "draw": true,
        "remove": true,
        "kamikaze": true,
        "name": "Kamikaze Attack",
    },
    {
        "num": 67,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "isr_agreement": true,
        "name": "Japanese Army/Navy",
    },
    {
        "num": 68,
        "faction": JP,
        "ops": 2,
        "type": POLITICAL,
        "oc": 4,
        "isr_agreement": true,
        "name": "Japanese Army/Navy",
    },
    {
        "num": 69,
        "faction": JP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 3,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "JN25 Code Change",
    },
    {
        "num": 70,
        "faction": JP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 3,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "JN25 Code Change",
    },
    {
        "num": 71,
        "faction": JP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 5,
        "remove": true,
        "name": "High Altitude Interceptors",
    },
    {
        "num": 72,
        "faction": JP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 5,
        "remove": true,
        "name": "Carrier Conversion",
    },
    {
        "num": 73,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 4,
        "ec": 6,
        "logistic": 3,
        "hq": [HQ_SOUTH_SEAS, HQ_JP_SOUTH],
        "remove": true,
        "name": "Ants",
    },
    {
        "num": 74,
        "faction": JP,
        "ops": 1,
        "type": POLITICAL,
        "oc": 3,
        "remove": true,
        "pw": -1,
        "name": "Tokyo Rose",
    },
    {
        "num": 75,
        "faction": JP,
        "ops": 1,
        "type": REACTION,
        "stage": BEFORE_COMBAT,
        "oc": 1,
        "draw": true,
        "name": "Submarine Attack",
    },
    {
        "num": 76,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 4,
        "ec": 6,
        "logistic": 1,
        "remove": true,
        "name": "Operation Tsurugi",
    },
    {
        "num": 77,
        "faction": JP,
        "ops": 3,
        "type": RESOURCE,
        "oc": 5,
        "name": "Fuel Shortage",
    },
    {
        "num": 78,
        "faction": JP,
        "ops": 1,
        "type": RESOURCE,
        "oc": 3,
        "remove": true,
        "name": "Tainan Air Unit",
    },
    {
        "num": 79,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 4,
        "ec": 6,
        "logistic": 1,
        "remove": true,
        "name": "Tinian Raid",
    },
    {
        "num": 80,
        "faction": JP,
        "ops": 2,
        "type": RESOURCE,
        "oc": 4,
        "draw": true,
        "remove": true,
        "name": "Attack on the Panama Canal",
    },
    {
        "num": 81,
        "faction": JP,
        "ops": 2,
        "type": REACTION,
        "stage": BEFORE_COMBAT,
        "oc": 4,
        "draw": true,
        "remove": true,
        "kamikaze": true,
        "name": "Kamikaze Attack",
    },
    {
        "num": 82,
        "faction": JP,
        "ops": 3,
        "type": POLITICAL,
        "oc": 5,
        "name": "Indian Worker's Strike",
    },
    {
        "num": 83,
        "faction": JP,
        "ops": 2,
        "type": MILITARY,
        "oc": 4,
        "ec": 6,
        "logistic": 4,
        "hq": [HQ_JP_SOUTH],
        "name": "Invasion of Java",
    },
    {
        "num": 84,
        "faction": JP,
        "ops": 1,
        "type": INTELLIGENCE,
        "oc": 3,
        "intelligence": INTERCEPT,
        "draw": true,
        "name": "JN25 Code Change",
    },
    {
        "num": 85,
        "faction": JP,
        "ops": 2,
        "type": COUNTER_OFFENSIVE,
        "oc": 4,
        "intelligence": INTERCEPT,
        "remove": true,
        "name": "Battle of Kolombanga",
    },
    {
        "num": 86,
        "faction": JP,
        "ops": 1,
        "type": REACTION,
        "stage": AFTER_COMBAT,
        "oc": 3,
        "draw": true,
        "name": "Submarine Attack",
    },
]

//cards
const OPERATION_NO_1 = find_card(JP, 2)
const OPERATION_C = find_card(JP, 8)
const COL_TSUJI = find_card(JP, 3)
const JN_25_SPECIAL = find_card(JP, 13)
const TOJO_RESIGNS = find_card(JP, 43)
const SHO_GO = find_card(JP, 45)
const GENERAL_ADACHI = find_card(JP, 48)
const MATADOR = find_card(AP, 5)
const DOOLITLE_RAID = find_card(AP, 6)
const ROCHEFORT = find_card(AP, 12)
const SKIP_BOMBING = find_card(AP, 24)
const SANDCRAB = find_card(AP, 30)
const DARTER_DACE = find_card(AP, 61)
const KING_II = find_card(AP, 62)
const SOVIET_INVADE = find_card(AP, 79)
const CARRIER_RAID = find_card(AP, 84)

function find_card(faction, num) {
    for (let i = 1; i < cards.length; i++) {
        if (cards[i].faction === faction && cards[i].num === num) {
            return i
        }
    }
    throw new Error(`Missed card ${faction} ${num}`);
}

function for_each_card(apply) {
    for (let i = 1; i < cards.length; i++) {
        var card = cards[i]
        var returned = apply(i, card)
        if (returned) {
            return returned
        }

    }
}